Add help to create plugin

diff --git a/script/create b/script/create
--- a/script/create
+++ b/script/create
@@ -149,6 +149,33 @@ function createPlugin {
 
 # ============ #
 
+# read type of file to be created
+type=${1,,}
+
+# ------------ #
+
+# check for errors while reading world
+if [[ ! $type ]] || [[ "$type" == "-p" ]] || [[  "$type" == "-n" ]]  ; then
+  err "Please choose the type of the file to be created."
+  exit 1
+fi
+
+# ------------ #
+
+# check for help
+if [[ "$type" == "--help" ]]  || [[ "$type" == "-h" ]]; then
+  echo -e "script/create - create elements of the Autbotz Simulator"
+  echo -e "SINTAXE: script/create type [options]"
+  echo -e "Types: world, model and plugin"
+  echo -e "Options:"
+  echo -e "\t -p: project - VSS, VT, GENERIC or TEST, default is GENERIC"
+  echo -e "\t -n: name - string without spaces, required"
+
+  exit 0
+fi
+
+# ------------ #
+
 #parse options
 project="GENERIC" # default project is GENERIC
 name_flag=False
@@ -160,6 +187,8 @@ while getopts p:n: option; do
   esac
 done
 
+# ------------ #
+
 # validate project
 valid_projects=(GENERIC VT VSS TEST)
 check_value valid_projects $project "Invalid project: ${project}!\nProjects available: ${valid_projects[*]}"
@@ -170,12 +199,15 @@ if [[ ! $name ]] ; then
   exit
 fi
 
-# format name
-## convert name in camelCase or PascalCase to snake_case
-name=$(echo ${name} | sed -r  -e 's:_(.):_\l\1:g' -e 's:([A-Z]):_\l\1:g' -e 's:^_::')
+# ------------ #
 
-# read type of file created
-type=${1,,}
+# format name
+## convert name in camelCase, PascalCase or kebab-case to snake_case
+name=$(echo ${name} | sed -r  -e 's:-:_:g' -e 's:_(.):_\l\1:g' -e 's:([A-Z]):_\l\1:g' -e 's:^_::')
+
+# ------------ #
+
+# create element
 case "${type}" in
   world) createWorld $project $name;;
   model) createModel $project $name;;
